version: '3'
services:

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: "always"
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=utu
    - POSTGRES_PASSWORD=abcd1234
    - POSTGRES_DB=bitcoin
    volumes:
    - ./config/postgres/data:/var/lib/postgresql/data
    - ./config/postgres/init-sql:/docker-entrypoint-initdb.d/
    - ./config/postgres/csv:/home/csv

  backend:
    image: node:latest
    container_name: backend
    restart: "always"
    ports:
    - "8000:8000"
    volumes:
    - ./backend:/home/backend
    working_dir: /home/backend
    depends_on:
    - postgres
    command: sh -c "npm install && node index.js"

  nginx:
    image: nginx:latest
    container_name: nginx
    network_mode: "host"
    restart: "always"
    volumes:
    - ./config/nginx/:/etc/nginx/conf.d/
    - ./frontend:/var/www/html