version: '3'
services:

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: "always"
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=utu
    - POSTGRES_PASSWORD=abcd1234
    - POSTGRES_DB=bitcoin
    volumes:
    - ./data:/var/lib/postgresql/data
    - ./init-sql:/docker-entrypoint-initdb.d/
    - ./csv:/home/csv

  backend:
    image: node:latest
    container_name: backend
    restart: "always"
    ports:
    - "8000:8000"
    volumes:
    - ./backend:/home/backend
    working_dir: /home/backend
    depends_on:
    - postgres
    command: bash -c "npm install && node index.js"