version: '3'
services:

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: "always"
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=utu
    - POSTGRES_PASSWORD=abcd1234
    - POSTGRES_DB=bitcoin
    volumes:
    - ./data:/var/lib/postgresql/data
    - ./init-sql:/docker-entrypoint-initdb.d/
    - ./csv:/home/csv
